menu:
- {name: 'Publications', url: '/publications'}
- {name: 'Presentations', url: '/presentations'}
- {name: 'Courses', url: '/courses'}
- {name: 'Travels', url: '/travels'}
- {name: 'Book Notes', url: '/booknotes'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

courses:
- {name: 'Seismology', url: 'seismology'}

social:
- {icon: 'github', link: 'https://github.com/diandarisma'}
- {icon: 'twitter', link: 'https://twitter.com/diandarisma'}
- {icon: 'google', link: 'https://scholar.google.co.id/citations?user=y87AIRoAAAAJ&hl=en&authuser=2'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/dian-darisma-58a96b71'}

contacts:
- {image: 'assets/img/kontak.jpeg'}
