menu:
- {name: 'Publications', url: '/publications'}
- {name: 'Presentations', url: '/presentations'}
- {name: 'Courses', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

courses:
- {name: 'Seismology', url: 'seismology'}

social:
- {icon: 'github', link: 'https://github.com/diandarisma'}
- {icon: 'twitter', link: 'https://twitter.com/diandarisma'}
- {icon: 'instagram', link: 'https://www.instagram.com/diandarisma/'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/dian-darisma-58a96b71'}

contacts:
- {image: 'assets/img/kontak.jpg'}
