menu:
- {name: 'Publications', url: '/publications'}
- {name: 'Presentations', url: '/presentations'}
- {name: 'Travels', url: '/travels'}
- {name: 'Book Notes', url: '/booknotes'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

courses:
- {name: 'Seismology', url: 'seismology'}

booknotes:
- {title: 'Atomic Habits', impression: 'This book is increasing my productivity. Sometimes people don’t know how to start working, but we can make it simple to make our work into small steps. So we can start from that part, although we make little progress because it is better than none.', image: 'assets/img/atomichabits.jpeg', url: 'atomichabits'}

social:
- {icon: 'github', link: 'https://github.com/diandarisma'}
- {icon: 'twitter', link: 'https://twitter.com/diandarisma'}
- {icon: 'google', link: 'https://scholar.google.co.id/citations?user=y87AIRoAAAAJ&hl=en&authuser=2'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/dian-darisma-58a96b71'}

contacts:
- {image: 'assets/img/kontak.jpeg'}
